name: foodadora
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animations: ^2.0.2
  badges: ^2.0.2
  cloud_firestore: ^3.1.7
  connectivity_plus: ^2.3.0
  copy_with_extension: ^4.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.0.0
  dotted_line: ^3.1.0
  equatable: ^2.0.5
  extended_image: ^6.3.1
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_translate: ^3.0.1
  form_builder_validators: ^7.2.0
  geocoding: ^2.0.5
  geoflutterfire2: ^2.3.11
  geolocator: ^8.2.0
  get: ^4.6.5
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  http: ^0.13.4
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  line_icons: ^2.0.1
  logger: ^1.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  stacked: ^2.3.3
  stacked_services: ^0.8.17
  touchable_opacity: ^1.2.0
  url_launcher: ^6.0.20

dev_dependencies:
  analyzer: ^4.7.0
  build_runner: null
  copy_with_extension_gen: ^4.0.3
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  stacked_generator: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/i18n/
