name: foodadora
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animations: ^2.0.2
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  dots_indicator: ^2.1.0
  dotted_line: ^3.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^7.0.0
  flutter_svg: ^1.0.3
  form_builder_validators: ^7.2.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  line_icons: ^2.0.1
  logger: ^1.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  stacked: ^2.2.8
  stacked_services: ^0.8.16
  flutter_translate: ^3.0.1
  injectable: ^1.5.3

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  stacked_generator: ^0.5.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/i18n/
